rj_smas_dev:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: rj-smas-dev
      dataset: dashboard_arcgis
      threads: 2
      keyfile: /etc/gcp/credentials/leoneabreu-smas.json
      timeout_seconds: 300
      location: US
