rj_smas_dev:
  # alvo-padrão para quem for rodar local: DEV
  target: dev
  outputs:
    prod:         
      type: bigquery
      method: service-account
      project: rj-smas-dev
      dataset: dashboard_arcgis
      keyfile: /etc/gcp/credentials/leoneabreu-smas.json
      threads: 2
      location: US
      timeout_seconds: 300

    dev:
      type: bigquery
      method: service-account
      project: rj-smas-dev
      dataset: dashboard_arcgis_dev
      keyfile: /etc/gcp/credentials/leoneabreu-smas.json
      threads: 2
      location: US
      timeout_seconds: 300
