name: CI · Build · Push

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:                              # 1️⃣ lint + pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt dbt-core dbt-bigquery
          pip install flake8 pytest

      - name: Lint
        continue-on-error: true
        run: flake8 pipeline

      - name: Tests
        run: pytest || echo "⚠️  Ainda sem testes — adicione depois"

  smoke-dbt:                         # 2️⃣ compila o dbt
    needs: test
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: ./queries    # onde está profiles.yml
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install dbt only
        run: pip install --quiet dbt-core dbt-bigquery

      - name: dbt compile
        run: |
          cd queries
          dbt parse            # ou: dbt compile

  build-push:                       # 3️⃣ publica imagem só se smoke OK
    needs: smoke-dbt
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
