name: CI · Build · Push

on:
  push:
    branches: [main]        
  pull_request:
  workflow_dispatch:        # permite disparo manual

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt dbt-core dbt-bigquery
          pip install flake8 pytest

      - name: Lint
        run: flake8 pipeline

      - name: Tests
        run: pytest || echo "⚠️  Ainda sem testes — adicione depois"

  build-push:
    needs: test              # só builda se os testes passarem
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write        # publicar no GHCR

    steps:
      - uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
